apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-ingress
  labels:
    release: {{ .Release.Name }}
  annotations:
    http.port: "443"
spec:
  serviceName: nginx
  servicePort: 80